$(document).ready(function(){
	$('#pc_specific').fadeIn(20000);
});
$(document).ready(function(){
	$('#solved_problem').fadeIn(30000);
});
$(document).ready(function(){
	$('#venue_location').fadeIn(40000);
});
$(document).ready(function(){
	$('#troubleshoot').fadeIn(50000);
});
$(document).ready(function(){
	$('#top_performers').fadeIn(60000);
});
$(document).ready(function(){
	$('#rounding_dashboard').fadeIn(30000);
});

//rounding_dashboard